#! /bin/sh

case "$1" in
	start)
		#start-stop-daemon -S -n aesdsocket -a "/usr/bin/aesdsocket" -- "-d"
		echo "starting a7 mods"
		/usr/bin/scull_load
		/usr/bin/module_load faulty
		#depmod
		modprobe hello
		modprobe i2c-dev
		modprobe i2c-bcm2835
		;;
	stop)
		#start-stop-daemon -K -n aesdsocket
		echo "killing a7 mods"
		/usr/bin/scull_unload
		/usr/bin/module_unload faulty
		rmmod hello
		rmmod i2c-dev
		rmmod i2c-bcm2835
		;;
	*)
	exit 1
esac
