#! /bin/sh

case "$1" in
	start)
		#start-stop-daemon -S -n aesdsocket -a "/usr/bin/aesdsocket" -- "-d"
		echo "starting a7 mods"
		/usr/bin/scull_load
		/usr/bin/module_load faulty
		modprobe /usr/bin/hello.ko
		;;
	stop)
		#start-stop-daemon -K -n aesdsocket
		echo "killing a7 mods"
		/usr/bin/scull_unload
		/usr/bin/module_unload faulty
		rmmod hello
		;;
	*)
	exit 1
esac
